// <auto-generated />
namespace KartRacingManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addLapTimeInMs_To_Laps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLapTimeInMs_To_Laps));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091527460_addLapTimeInMs_To_Laps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
