// <auto-generated />
namespace KartRacingManager.Data.SqliteMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_log_message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_log_message));
        
        string IMigrationMetadata.Id
        {
            get { return "201706092305529_add_log_message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
